  
FROM nginx:1.13

COPY ./.docker-config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./.docker-config/nginx/conf.d /etc/nginx/user.conf.d
# COPY ./.docker-config/nginx/letsencrypt/ /etc/letsencrypt/   
