  
FROM staticfloat/nginx-certbot

ENV CERTBOT_EMAIL="christopher.jativa320@outlook.com"
# ENV IS_STAGING=1
COPY ./.docker-config/nginx/conf.d /etc/nginx/user.conf.d
# ./.docker-config/php/src/web /var/www/html/web